language: android 

android:
  components:
    - platform-tools  
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - chmod +x ./gradlew

script:
    - ./gradlew clean build

deploy:
  provider: script
  script: chmod +x ./gradlew && ./gradlew :floatinghover:clean :floatinghover:build :floatinghover:install :floatinghover:bintrayUpload
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    branch: master